- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    password: admin123
    url: http://172.31.0.152:8080
    user: admin

- name: Create a multibranch pipeline
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/mbranch.xml') }}"
    name: testm
    password: admin123
    url: http://172.31.0.152:8080
    user: admin
